//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySupply {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class L {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal L() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySupply.L", typeof(L).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acenta.
        /// </summary>
        internal static string Acenta {
            get {
                return ResourceManager.GetString("Acenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adet.
        /// </summary>
        internal static string Adet {
            get {
                return ResourceManager.GetString("Adet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adı.
        /// </summary>
        internal static string Adi {
            get {
                return ResourceManager.GetString("Adi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres.
        /// </summary>
        internal static string Adres {
            get {
                return ResourceManager.GetString("Adres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktarılacak Excel Dosyası.
        /// </summary>
        internal static string AktarilacakExcelDosyasi {
            get {
                return ResourceManager.GetString("AktarilacakExcelDosyasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktarım Dosyası.
        /// </summary>
        internal static string AktarimDosyasi {
            get {
                return ResourceManager.GetString("AktarimDosyasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algılanan değişiklikler renklendirilmiştir üzerinde değişiklik yaparak kaydedebilirsiniz..
        /// </summary>
        internal static string AlgilananDegisiklikler {
            get {
                return ResourceManager.GetString("AlgilananDegisiklikler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B. Fiyatı.
        /// </summary>
        internal static string AlisFiyati {
            get {
                return ResourceManager.GetString("AlisFiyati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.Fiyat Tutar.
        /// </summary>
        internal static string AlisTutar {
            get {
                return ResourceManager.GetString("AlisTutar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arşivdeki Bilgileri Süz.
        /// </summary>
        internal static string ArsivdekiBilgileriSuz {
            get {
                return ResourceManager.GetString("ArsivdekiBilgileriSuz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayarları Ağ&apos;dan Al.
        /// </summary>
        internal static string AyarlariAgdanAl {
            get {
                return ResourceManager.GetString("AyarlariAgdanAl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayarları Kaydet.
        /// </summary>
        internal static string AyarlariKaydet {
            get {
                return ResourceManager.GetString("AyarlariKaydet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bağlama Limanı.
        /// </summary>
        internal static string BaglamaLimani {
            get {
                return ResourceManager.GetString("BaglamaLimani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form başlığında resim kullanılıyor!.
        /// </summary>
        internal static string BasliktaResimKullaniliyor {
            get {
                return ResourceManager.GetString("BasliktaResimKullaniliyor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form başlığında resim kullanmak için tıklayın!.
        /// </summary>
        internal static string BasliktaResimKullanin {
            get {
                return ResourceManager.GetString("BasliktaResimKullanin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilinmeyen!.
        /// </summary>
        internal static string Bilinmeyen {
            get {
                return ResourceManager.GetString("Bilinmeyen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birim.
        /// </summary>
        internal static string Birim {
            get {
                return ResourceManager.GetString("Birim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boş geçilemez...
        /// </summary>
        internal static string BosGecilemez {
            get {
                return ResourceManager.GetString("BosGecilemez", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Değişiklikleri Algıla!.
        /// </summary>
        internal static string DegisiklikAlgila {
            get {
                return ResourceManager.GetString("DegisiklikAlgila", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destek Hattına mesaj iletilemedi lütfen tekrar deneyiniz!.
        /// </summary>
        internal static string DestekBildirimBasarisiz {
            get {
                return ResourceManager.GetString("DestekBildirimBasarisiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destek Hattına mesaj başarılı bir şekilde gönderildi!.
        /// </summary>
        internal static string DestekBildirimIletildi {
            get {
                return ResourceManager.GetString("DestekBildirimIletildi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aşağıdaki konu ile ilgili yardımınızı rica ediyorum!.
        /// </summary>
        internal static string DestekBildirimKonusu {
            get {
                return ResourceManager.GetString("DestekBildirimKonusu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destek Hattı.
        /// </summary>
        internal static string DestekHatti {
            get {
                return ResourceManager.GetString("DestekHatti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detaylar.
        /// </summary>
        internal static string Detaylar {
            get {
                return ResourceManager.GetString("Detaylar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diğer firmalardan alınan teklife göre içeri aktarılacak ürünler aşağıdaki gibidir!.
        /// </summary>
        internal static string DigerFirmadanTeklifAktarim {
            get {
                return ResourceManager.GetString("DigerFirmadanTeklifAktarim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dışarı Aktar.
        /// </summary>
        internal static string DisariAktar {
            get {
                return ResourceManager.GetString("DisariAktar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doviz Kurları.
        /// </summary>
        internal static string DovizKurlari {
            get {
                return ResourceManager.GetString("DovizKurlari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burada belirttiğiniz doviz kuru diğer para birimi alanlarındaki ile aynı olmamalıdır!.
        /// </summary>
        internal static string DovizKuruBelirtilmis {
            get {
                return ResourceManager.GetString("DovizKuruBelirtilmis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durum.
        /// </summary>
        internal static string Durum {
            get {
                return ResourceManager.GetString("Durum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eklenme Tarihi.
        /// </summary>
        internal static string EklenmeTarihi {
            get {
                return ResourceManager.GetString("EklenmeTarihi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En Ucuz Ürünlerin Listesi.
        /// </summary>
        internal static string EnUcuzUrunListesi {
            get {
                return ResourceManager.GetString("EnUcuzUrunListesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel dosyasını geri alma işlemi başarılı bir şekilde gerçekleşti!.
        /// </summary>
        internal static string ExcelAktarimDosyasiMesaji {
            get {
                return ResourceManager.GetString("ExcelAktarimDosyasiMesaji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilgi : Excel&apos;deki &apos;{0}&apos; ürün başarılı bir şekilde aktarıldı!.
        /// </summary>
        internal static string ExcelDekiUrunAktarildi {
            get {
                return ResourceManager.GetString("ExcelDekiUrunAktarildi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FATURA.
        /// </summary>
        internal static string Fatura {
            get {
                return ResourceManager.GetString("Fatura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatura Hazırla.
        /// </summary>
        internal static string FaturaHazirla {
            get {
                return ResourceManager.GetString("FaturaHazirla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firma.
        /// </summary>
        internal static string Firma {
            get {
                return ResourceManager.GetString("Firma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} tedarikci firmanin fiyat listesi..
        /// </summary>
        internal static string FirmaninFiyatListesi {
            get {
                return ResourceManager.GetString("FirmaninFiyatListesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} isimli firma stok kayıtlarında var bu sebebden dolayı silemezsiniz..
        /// </summary>
        internal static string FirmaninStoklariVarSilinemez {
            get {
                return ResourceManager.GetString("FirmaninStoklariVarSilinemez", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firma Tanımla.
        /// </summary>
        internal static string FirmaTanimla {
            get {
                return ResourceManager.GetString("FirmaTanimla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formu Yenile.
        /// </summary>
        internal static string FormuYenile {
            get {
                return ResourceManager.GetString("FormuYenile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talebiniz tarafımıza ulaştı iletişim bilgileriniz üzerinden sizinle irtibata geçilecektir..
        /// </summary>
        internal static string FullLisansTalebi {
            get {
                return ResourceManager.GetString("FullLisansTalebi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taleb mailinizi gönderme esnasında bir hata oluştu lütfen internet bağlatınızı kontrol ediniz..
        /// </summary>
        internal static string FullLisansTalebiHata {
            get {
                return ResourceManager.GetString("FullLisansTalebiHata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gemi İsmi.
        /// </summary>
        internal static string GemiAdi {
            get {
                return ResourceManager.GetString("GemiAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gönder.
        /// </summary>
        internal static string Gonder {
            get {
                return ResourceManager.GetString("Gonder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncelle.
        /// </summary>
        internal static string Guncelle {
            get {
                return ResourceManager.GetString("Guncelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncelleme Tarihi.
        /// </summary>
        internal static string GuncellemeTarihi {
            get {
                return ResourceManager.GetString("GuncellemeTarihi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hatayı göndermek için tıklayın!.
        /// </summary>
        internal static string HataBildirimiYap {
            get {
                return ResourceManager.GetString("HataBildirimiYap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hazırlayan.
        /// </summary>
        internal static string Hazirlayan {
            get {
                return ResourceManager.GetString("Hazirlayan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hızlı Stok Girişi.
        /// </summary>
        internal static string HizliStokGirisi {
            get {
                return ResourceManager.GetString("HizliStokGirisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İçeri Aktar.
        /// </summary>
        internal static string IceriAktar {
            get {
                return ResourceManager.GetString("IceriAktar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID ile Aktar!.
        /// </summary>
        internal static string IDAktarimi {
            get {
                return ResourceManager.GetString("IDAktarimi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belirlenen ID&apos;lere göre bulunan ürünler aşağıdaki gibidir!.
        /// </summary>
        internal static string IDileAktarimMesaji {
            get {
                return ResourceManager.GetString("IDileAktarimMesaji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kabul ediyorum!.
        /// </summary>
        internal static string KabulEdiyorum {
            get {
                return ResourceManager.GetString("KabulEdiyorum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kabul etmek için tıklayın!.
        /// </summary>
        internal static string KabulEtmek {
            get {
                return ResourceManager.GetString("KabulEtmek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kar %.
        /// </summary>
        internal static string KarOrani {
            get {
                return ResourceManager.GetString("KarOrani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uyarı: Lütfen excel aktarım işlemlerini yapmadan önce &apos;Kâr Oranı&apos; belirleyiniz!.
        /// </summary>
        internal static string KarOraniBelirle {
            get {
                return ResourceManager.GetString("KarOraniBelirle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Kâr Orani Belirleme.
        /// </summary>
        internal static string KarOraniDegistir {
            get {
                return ResourceManager.GetString("KarOraniDegistir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçilen Firma Dışındakilere Uygula.
        /// </summary>
        internal static string KarOraniFirmaDisindakilere {
            get {
                return ResourceManager.GetString("KarOraniFirmaDisindakilere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçilen Kategori Dışındakilere Uygula.
        /// </summary>
        internal static string KarOraniKategoriDisindakilere {
            get {
                return ResourceManager.GetString("KarOraniKategoriDisindakilere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçilen Kategori ve/veya Firma Dışındakilere Uygula.
        /// </summary>
        internal static string KarOraniSecilenDisindakilereUygula {
            get {
                return ResourceManager.GetString("KarOraniSecilenDisindakilereUygula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçilen Kategoriye ve/veya Firmaya Uygula.
        /// </summary>
        internal static string KarOraniSecileneUygula {
            get {
                return ResourceManager.GetString("KarOraniSecileneUygula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filitresiz Tümüne Uyugula.
        /// </summary>
        internal static string KarOraniTumuneUygula {
            get {
                return ResourceManager.GetString("KarOraniTumuneUygula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Kâr Oranı % (0,00).
        /// </summary>
        internal static string KarOraniYeni {
            get {
                return ResourceManager.GetString("KarOraniYeni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori.
        /// </summary>
        internal static string Kategori {
            get {
                return ResourceManager.GetString("Kategori", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} kategori içerisindeki ürünlerin listesi..
        /// </summary>
        internal static string KategoridekiUrunListesi {
            get {
                return ResourceManager.GetString("KategoridekiUrunListesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori Tanımla.
        /// </summary>
        internal static string KategoriTanimla {
            get {
                return ResourceManager.GetString("KategoriTanimla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} kategorisine ürünler başarılı bir şekilde eklendi..
        /// </summary>
        internal static string KategoriUrunlerEklendi {
            get {
                return ResourceManager.GetString("KategoriUrunlerEklendi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydet.
        /// </summary>
        internal static string Kaydet {
            get {
                return ResourceManager.GetString("Kaydet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K.D.V..
        /// </summary>
        internal static string KDV {
            get {
                return ResourceManager.GetString("KDV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod.
        /// </summary>
        internal static string Kod {
            get {
                return ResourceManager.GetString("Kod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konu.
        /// </summary>
        internal static string Konu {
            get {
                return ResourceManager.GetString("Konu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydedilen Kur Bilgisi.
        /// </summary>
        internal static string KurKaydedilen {
            get {
                return ResourceManager.GetString("KurKaydedilen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doviz Kurunu Güncelle.
        /// </summary>
        internal static string KurYeni {
            get {
                return ResourceManager.GetString("KurYeni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen yüklemek istediğiniz lisans dosyasını seçiniz!.
        /// </summary>
        internal static string LisansDosyasiSec {
            get {
                return ResourceManager.GetString("LisansDosyasiSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belirtiğiniz lisans dosyası geçersiz lütfen bizimle irtibata geçerek yeni lisans dosyası talep ediniz..
        /// </summary>
        internal static string LisansGecersiz {
            get {
                return ResourceManager.GetString("LisansGecersiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belirtiğiniz mail adresi geçersizdir..
        /// </summary>
        internal static string MailGecersiz {
            get {
                return ResourceManager.GetString("MailGecersiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        internal static string Manager {
            get {
                return ResourceManager.GetString("Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesaj Detayları.
        /// </summary>
        internal static string MesajDetaylari {
            get {
                return ResourceManager.GetString("MesajDetaylari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miktar.
        /// </summary>
        internal static string Miktar {
            get {
                return ResourceManager.GetString("Miktar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri Bilgileri.
        /// </summary>
        internal static string Musteri {
            get {
                return ResourceManager.GetString("Musteri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri tarafından miktar üzerinde yapılan değişiklikler aşağıdaki gibidir!.
        /// </summary>
        internal static string MusteriDegisikligiAktarim {
            get {
                return ResourceManager.GetString("MusteriDegisikligiAktarim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Kâr.
        /// </summary>
        internal static string NetKar {
            get {
                return ResourceManager.GetString("NetKar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not.
        /// </summary>
        internal static string Not {
            get {
                return ResourceManager.GetString("Not", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ödeme Yolu.
        /// </summary>
        internal static string OdemeYolu {
            get {
                return ResourceManager.GetString("OdemeYolu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu bölümde yapılacak değişiklikler önem arz etmektedir!.
        /// </summary>
        internal static string OnemliUyari {
            get {
                return ResourceManager.GetString("OnemliUyari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para Birimi.
        /// </summary>
        internal static string ParaBirimi {
            get {
                return ResourceManager.GetString("ParaBirimi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        internal static string Period {
            get {
                return ResourceManager.GetString("Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referans numarasına göre ilgili teklifi getirir..
        /// </summary>
        internal static string ReferNoUyari {
            get {
                return ResourceManager.GetString("ReferNoUyari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S. Fiyatı.
        /// </summary>
        internal static string SatisFiyati {
            get {
                return ResourceManager.GetString("SatisFiyati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.Fiyat Tutar.
        /// </summary>
        internal static string SatisTutar {
            get {
                return ResourceManager.GetString("SatisTutar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sepete Ürün Ekleyin.
        /// </summary>
        internal static string SepeteUrunEkle {
            get {
                return ResourceManager.GetString("SepeteUrunEkle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sepeti Geri Al.
        /// </summary>
        internal static string SepetiGeriAl {
            get {
                return ResourceManager.GetString("SepetiGeriAl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sipariş Maliyet Listesi.
        /// </summary>
        internal static string SiparisMaliyetListesi {
            get {
                return ResourceManager.GetString("SiparisMaliyetListesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sipariş Toplama Listesi.
        /// </summary>
        internal static string SiparisToplamaListesi {
            get {
                return ResourceManager.GetString("SiparisToplamaListesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sıra No.
        /// </summary>
        internal static string SiraNo {
            get {
                return ResourceManager.GetString("SiraNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stok Girişi.
        /// </summary>
        internal static string StokGirisi {
            get {
                return ResourceManager.GetString("StokGirisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Stok Tanımlama.
        /// </summary>
        internal static string StokTanimla {
            get {
                return ResourceManager.GetString("StokTanimla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Süz.
        /// </summary>
        internal static string Suz {
            get {
                return ResourceManager.GetString("Suz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAMAM.
        /// </summary>
        internal static string Tamam {
            get {
                return ResourceManager.GetString("Tamam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarih.
        /// </summary>
        internal static string Tarih {
            get {
                return ResourceManager.GetString("Tarih", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlk Tarih.
        /// </summary>
        internal static string TarihIlk {
            get {
                return ResourceManager.GetString("TarihIlk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son Tarih.
        /// </summary>
        internal static string TarihSon {
            get {
                return ResourceManager.GetString("TarihSon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELIVERY EXPENSES / TAŞIMA ÜCRETİ.
        /// </summary>
        internal static string TasimaHizmetBedeli {
            get {
                return ResourceManager.GetString("TasimaHizmetBedeli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taşıma Ücreti.
        /// </summary>
        internal static string TasimaUcreti {
            get {
                return ResourceManager.GetString("TasimaUcreti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tedarikçi Firma.
        /// </summary>
        internal static string TedarikciFirma {
            get {
                return ResourceManager.GetString("TedarikciFirma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEKLİYOR.
        /// </summary>
        internal static string Teklif_BEKLIYOR {
            get {
                return ResourceManager.GetString("Teklif_BEKLIYOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İPTAL.
        /// </summary>
        internal static string Teklif_IPTAL {
            get {
                return ResourceManager.GetString("Teklif_IPTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ONAYLANDI.
        /// </summary>
        internal static string Teklif_ONAYLANDI {
            get {
                return ResourceManager.GetString("Teklif_ONAYLANDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teklif Arşivi.
        /// </summary>
        internal static string TeklifArsivi {
            get {
                return ResourceManager.GetString("TeklifArsivi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teklif Durumunu Değiştirin.
        /// </summary>
        internal static string TeklifDurumuBelirleyin {
            get {
                return ResourceManager.GetString("TeklifDurumuBelirleyin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teklif Kaydet.
        /// </summary>
        internal static string TeklifKaydet {
            get {
                return ResourceManager.GetString("TeklifKaydet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teklifleri Birleştir!.
        /// </summary>
        internal static string TeklifleriBirlestir {
            get {
                return ResourceManager.GetString("TeklifleriBirlestir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teklif Verme Tutanağı.
        /// </summary>
        internal static string TeklifVermeTutanagi {
            get {
                return ResourceManager.GetString("TeklifVermeTutanagi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        internal static string Telefon {
            get {
                return ResourceManager.GetString("Telefon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temizle.
        /// </summary>
        internal static string Temizle {
            get {
                return ResourceManager.GetString("Temizle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teslimat.
        /// </summary>
        internal static string TeslimatSarti {
            get {
                return ResourceManager.GetString("TeslimatSarti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malzeme Teslim Tutanağı.
        /// </summary>
        internal static string TeslimVermeTutanagi {
            get {
                return ResourceManager.GetString("TeslimVermeTutanagi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tüm Firmalara Uygula.
        /// </summary>
        internal static string TumFirmalaraUygula {
            get {
                return ResourceManager.GetString("TumFirmalaraUygula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tüm Kategorilere Uygula.
        /// </summary>
        internal static string TumKategorilereUygula {
            get {
                return ResourceManager.GetString("TumKategorilereUygula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tüm Ürünlerin Listesi.
        /// </summary>
        internal static string TumUrunListesi {
            get {
                return ResourceManager.GetString("TumUrunListesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Açıklaması.
        /// </summary>
        internal static string UrunAciklama {
            get {
                return ResourceManager.GetString("UrunAciklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Fiyatı Karşılatırma.
        /// </summary>
        internal static string UrunFiyatKarislastirma {
            get {
                return ResourceManager.GetString("UrunFiyatKarislastirma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürünler başarılı bir şekilde güncellendi..
        /// </summary>
        internal static string UrunlerGuncellendi {
            get {
                return ResourceManager.GetString("UrunlerGuncellendi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products Filter.
        /// </summary>
        internal static string UrunleriFlitrele {
            get {
                return ResourceManager.GetString("UrunleriFlitrele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} isimli ürün stok kayıtlarında var bu sebebden dolayı silemezsiniz..
        /// </summary>
        internal static string UrunStokdaVarSilinmez {
            get {
                return ResourceManager.GetString("UrunStokdaVarSilinmez", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uygulama Ayarları.
        /// </summary>
        internal static string UygulamAyarlari {
            get {
                return ResourceManager.GetString("UygulamAyarlari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAZGEÇ.
        /// </summary>
        internal static string Vazgec {
            get {
                return ResourceManager.GetString("Vazgec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ağ&apos;daki Veritabanı.
        /// </summary>
        internal static string VeritabaniAgdanSec {
            get {
                return ResourceManager.GetString("VeritabaniAgdanSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veritabanı Dosya Yolu.
        /// </summary>
        internal static string VeritabaniDosyaYolu {
            get {
                return ResourceManager.GetString("VeritabaniDosyaYolu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veritabanı Geri Al.
        /// </summary>
        internal static string VeritabaniGeriAl {
            get {
                return ResourceManager.GetString("VeritabaniGeriAl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veriabanını yedekten geri alma işlemi için güvenlik kodunu girmeniz gerekmektedir..
        /// </summary>
        internal static string VeritabaniGerialIslemiSifre {
            get {
                return ResourceManager.GetString("VeritabaniGerialIslemiSifre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu işlem sırasında verileriniz en son yedekleme anına dönecektir. Kabul ediyor musunuz?.
        /// </summary>
        internal static string VeritabaniGerialIslemiUyari {
            get {
                return ResourceManager.GetString("VeritabaniGerialIslemiUyari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veritabanı yedekden geri alma işlemi başarılı bir şekilde gerçekleşti!.
        /// </summary>
        internal static string VeritabaniGeriAlmaIslemi {
            get {
                return ResourceManager.GetString("VeritabaniGeriAlmaIslemi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Veritabanı Oluştur.
        /// </summary>
        internal static string VeritabaniOlustur {
            get {
                return ResourceManager.GetString("VeritabaniOlustur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni veritabanı oluşturuldu..
        /// </summary>
        internal static string VeritabaniOlusturmaIslemi {
            get {
                return ResourceManager.GetString("VeritabaniOlusturmaIslemi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veritabanı Onar.
        /// </summary>
        internal static string VeritabaniOnar {
            get {
                return ResourceManager.GetString("VeritabaniOnar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veritabanı onarma işlemi başarılı bir şekilde gerçekleşti!.
        /// </summary>
        internal static string VeritabaniOnarmaIslemi {
            get {
                return ResourceManager.GetString("VeritabaniOnarmaIslemi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veritabanı Yedekle.
        /// </summary>
        internal static string VeritabaniYedekle {
            get {
                return ResourceManager.GetString("VeritabaniYedekle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veritabanı yedekleme işlemi başarılı bir şekilde gerçekleşti!.
        /// </summary>
        internal static string VeritabaniYedeklemeIslemi {
            get {
                return ResourceManager.GetString("VeritabaniYedeklemeIslemi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Dosya Adı.
        /// </summary>
        internal static string YeniDosyaAdi {
            get {
                return ResourceManager.GetString("YeniDosyaAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Kategori.
        /// </summary>
        internal static string YeniKategori {
            get {
                return ResourceManager.GetString("YeniKategori", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Kayıt.
        /// </summary>
        internal static string YeniKayit {
            get {
                return ResourceManager.GetString("YeniKayit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Lisans Satın Al.
        /// </summary>
        internal static string YeniLisansSatinAl {
            get {
                return ResourceManager.GetString("YeniLisansSatinAl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Tedarikçi Firma.
        /// </summary>
        internal static string YeniTedarikciFirma {
            get {
                return ResourceManager.GetString("YeniTedarikciFirma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Teklif Hazırla.
        /// </summary>
        internal static string YeniTeklifHazirla {
            get {
                return ResourceManager.GetString("YeniTeklifHazirla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Ürün.
        /// </summary>
        internal static string YeniUrun {
            get {
                return ResourceManager.GetString("YeniUrun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategoriye Yeni Ürün Ekle.
        /// </summary>
        internal static string YeniUrunKategoriBazinda {
            get {
                return ResourceManager.GetString("YeniUrunKategoriBazinda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Ürün Tanımla.
        /// </summary>
        internal static string YeniUrunTanimla {
            get {
                return ResourceManager.GetString("YeniUrunTanimla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yetkili Personel.
        /// </summary>
        internal static string Yetkili {
            get {
                return ResourceManager.GetString("Yetkili", resourceCulture);
            }
        }
    }
}
